# Generated by Django 5.1.2 on 2024-12-28 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0007_alter_transaction_receiver_alter_transaction_sender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='user',
        ),
    ]
