# Generated by Django 5.1.2 on 2024-12-30 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0008_remove_transaction_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='TransactionType',
            field=models.CharField(default='TRANSFER', max_length=20),
        ),
        migrations.AddField(
            model_name='transaction',
            name='value_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
