# Generated by Django 5.0.6 on 2024-06-24 19:27

import account.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccountminor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(default=account.models.generate_unique_account_number, editable=False, max_length=16, unique=True)),
                ('account_holder_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('current_address', models.TextField(default='')),
                ('Permanent_Address', models.CharField(max_length=100)),
                ('sex', models.CharField(default=None, max_length=1)),
                ('annual_income', models.IntegerField(default=0)),
                ('occupation', models.CharField(default=None, max_length=50, null=True)),
                ('country', models.CharField(default='India', max_length=50)),
                ('state', models.CharField(default='kerala', max_length=50)),
                ('city', models.CharField(default='delhi', max_length=50)),
                ('street', models.CharField(default='main lane', max_length=50)),
                ('pincode', models.IntegerField(default='123456')),
                ('phone_number', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(code='invalid_phone_number', message='Phone number must be between 10 and 15 digits', regex='^\\d{10}$')])),
                ('email', models.EmailField(blank=True, max_length=100)),
                ('aadhar_number', models.CharField(blank=True, max_length=12, validators=[django.core.validators.RegexValidator(code='invalid_aadhar_number', message='Aadhar number must be exactly 12 digits', regex='^\\d{12}$')])),
                ('passport_number', models.CharField(blank=True, max_length=9, validators=[django.core.validators.RegexValidator(code='invalid_passport_number', message='Invalid passport number', regex='^[A-PR-WYa-pr-wy][1-9]\\d\\s?\\d{4}[1-9]$')])),
                ('voter_id_number', models.CharField(blank=True, max_length=10, validators=[django.core.validators.RegexValidator(code='invalid_voter_id_number', message='Voter ID number must be 3 letters followed by 7 digits', regex='^[A-Z]{3}[0-9]{7}$')])),
                ('pan_card_number', models.CharField(blank=True, max_length=10, validators=[django.core.validators.RegexValidator(code='invalid_pan_card_number', message='PAN card number must be 5 letters followed by 4 digits and 1 letter', regex='^[A-Z]{5}[0-9]{4}[A-Z]$')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='BankAccountsenior',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(default=account.models.generate_unique_account_number, editable=False, max_length=16, unique=True)),
                ('account_holder_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('current_address', models.TextField(default='')),
                ('Permanent_Address', models.CharField(max_length=100)),
                ('sex', models.CharField(default=None, max_length=1)),
                ('annual_income', models.IntegerField(default=0)),
                ('occupation', models.CharField(default=None, max_length=50, null=True)),
                ('country', models.CharField(default='India', max_length=50)),
                ('state', models.CharField(default='kerala', max_length=50)),
                ('city', models.CharField(default='delhi', max_length=50)),
                ('street', models.CharField(default='main lane', max_length=50)),
                ('pincode', models.IntegerField(default='123456')),
                ('phone_number', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(code='invalid_phone_number', message='Phone number must be between 10 and 15 digits', regex='^\\d{10,15}$')])),
                ('email', models.EmailField(blank=True, max_length=100)),
                ('aadhar_number', models.CharField(blank=True, max_length=12, validators=[django.core.validators.RegexValidator(code='invalid_aadhar_number', message='Aadhar number must be exactly 12 digits', regex='^\\d{12}$')])),
                ('passport_number', models.CharField(blank=True, max_length=9, validators=[django.core.validators.RegexValidator(code='invalid_passport_number', message='Invalid passport number', regex='^[A-PR-WYa-pr-wy][1-9]\\d\\s?\\d{4}[1-9]$')])),
                ('voter_id_number', models.CharField(blank=True, max_length=10, validators=[django.core.validators.RegexValidator(code='invalid_voter_id_number', message='Voter ID number must be 3 letters followed by 7 digits', regex='^[A-Z]{3}[0-9]{7}$')])),
                ('pan_card_number', models.CharField(blank=True, max_length=10, validators=[django.core.validators.RegexValidator(code='invalid_pan_card_number', message='PAN card number must be 5 letters followed by 4 digits and 1 letter', regex='^[A-Z]{5}[0-9]{4}[A-Z]$')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(default=account.models.generate_unique_account_number, editable=False, max_length=16, unique=True)),
                ('account_holder_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('current_address', models.TextField(default='')),
                ('Permanent_Address', models.CharField(max_length=100)),
                ('sex', models.CharField(default=None, max_length=1)),
                ('annual_income', models.IntegerField(default=0)),
                ('occupation', models.CharField(blank=True, max_length=50, null=True)),
                ('country', models.CharField(default='India', max_length=50)),
                ('state', models.CharField(default='kerala', max_length=50)),
                ('city', models.CharField(default='delhi', max_length=50)),
                ('street', models.CharField(default='main lane', max_length=50)),
                ('pincode', models.IntegerField(default='123456')),
                ('phone_number', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(code='invalid_phone_number', message='Phone number must be between 10 and 15 digits', regex='^\\d{10}$')])),
                ('email', models.EmailField(blank=True, max_length=100)),
                ('aadhar_number', models.CharField(blank=True, max_length=12, validators=[django.core.validators.RegexValidator(code='invalid_aadhar_number', message='Aadhar number must be exactly 12 digits', regex='^\\d{12}$')])),
                ('passport_number', models.CharField(blank=True, max_length=9, validators=[django.core.validators.RegexValidator(code='invalid_passport_number', message='Invalid passport number', regex='^[A-PR-WYa-pr-wy][1-9]\\d\\s?\\d{4}[1-9]$')])),
                ('voter_id_number', models.CharField(blank=True, max_length=10, validators=[django.core.validators.RegexValidator(code='invalid_voter_id_number', message='Voter ID number must be 3 letters followed by 7 digits', regex='^[A-Z]{3}[0-9]{7}$')])),
                ('pan_card_number', models.CharField(blank=True, max_length=10, validators=[django.core.validators.RegexValidator(code='invalid_pan_card_number', message='PAN card number must be 5 letters followed by 4 digits and 1 letter', regex='^[A-Z]{5}[0-9]{4}[A-Z]$')])),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
