# Generated by Django 5.0.6 on 2024-07-18 14:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='phone_number',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(code='invalid_phone_number', message='Phone number must be exactly 10 digits', regex='^\\d{10}$')]),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='pincode',
            field=models.IntegerField(default=123456),
        ),
    ]
