# Generated by Django 5.1.2 on 2024-11-18 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_customuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccountminor',
            name='name_of_guardian',
            field=models.CharField(default='Default Name', max_length=255),
        ),
    ]
