# Generated by Django 5.1.2 on 2025-01-13 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_bankaccountminor_name_of_guardian'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccountminor',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='bankaccountsenior',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
