# Generated by Django 5.1.2 on 2026-05-11 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_bankaccountminor_balance_bankaccountsenior_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankaccountminor',
            name='balance',
        ),
        migrations.RemoveField(
            model_name='bankaccountminor',
            name='name_of_guardian',
        ),
        migrations.RemoveField(
            model_name='bankaccountsenior',
            name='balance',
        ),
    ]
