# Generated by Django 5.1.2 on 2026-05-11 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_remove_bankaccountminor_balance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='sex',
            field=models.CharField(default=None, max_length=10),
        ),
        migrations.AlterField(
            model_name='bankaccountminor',
            name='sex',
            field=models.CharField(default=None, max_length=10),
        ),
        migrations.AlterField(
            model_name='bankaccountsenior',
            name='sex',
            field=models.CharField(default=None, max_length=10),
        ),
    ]
