# Generated by Django 5.1.2 on 2026-05-11 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_alter_bankaccount_sex_alter_bankaccountminor_sex_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='is_frozen',
            field=models.BooleanField(default=False),
        ),
    ]
