# Generated by Django 5.1.2 on 2026-05-15 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_add_card_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardrequest',
            name='card_number',
            field=models.CharField(blank=True, max_length=16, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='cardrequest',
            name='cvv',
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.AddField(
            model_name='cardrequest',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
